### ISSUE TITLE
Consider simplifying type parameterization for view execution

### ISSUE THREAD

**Issue by cmbrandenburg** [chill-rs/chill#40]
The `ExecuteView` action, along with related types such as `ViewResponse`, require applications to explicitly provide Key and Value type parameters. Consider changing the API to allow for type inference.

**Comment by jgillich** [comment]
Maybe that could also allow one to ignore the value field ( when `value: null`). Since Rust doesn't have a `null` representation, you currently have to work around that with `Option<Something>`.

**Comment by cmbrandenburg** [comment]
I kinda like `Option<T>` for type-safety reasons, but I'm open to ideas.
