### ISSUE TITLE
Consider generalizing the transport layer regarding queries and bodies

### ISSUE THREAD

**Issue by cmbrandenburg** [chill-rs/chill#51]
Currently, the transport layer is specific to the CouchDB API. For example, the [`RequestOptions`](https://github.com/chill-rs/chill/blob/766784f19fdf2c8aad12d02d6f71ca6b1f7eaa94/src/transport/mod.rs#L68-L80) struct contains values for CouchDB-specific query parameters. Consequently, to add support for a new query parameter, the programmer must extend `RequestOptions` by adding a new field, as well as touching several other points in the transport layer to handle that new field.

**Comment by jgillich** [comment]
FWIW, I've played a bit with the idea, but I didn't really manage to reduce much boilerplate. The main issue is turning a `RequestOptions` struct into the actual request, which isn't really possible without assuming a specific protocol. A custom struct could implement traits like `IntoHttpRequest` etc, but that feels like over-engineering and you'll probably end up with as much code as before.

Maybe I was just over-thinking it, but if you can come up with something, I'd love to see that. :)

**Comment by cmbrandenburg** [comment]
@jgillich Ok, done. The new transport layer has no CouchDB-specific information in it and _might_ serve as a starting point for a separate crate—though I still have no definite plans to start a new crate.
