### ISSUE TITLE
New action to execute a view

### ISSUE THREAD

**Issue by cmbrandenburg** [chill-rs/chill#7]
Design and implement a new action type for executing a view. Use default values for all options.

**Comment by jgillich** [comment]
I've started working on this, however the path parsing stuff doesn't currently handle paths with more than 3 segments, like `/{db}/_design/{ddoc}/_view/{view}`. Should we add types like `ViewPath` and `DesignDocumentPath`, or do you have anything else in mind?

**Comment by jgillich** [comment]
I also just realized that it also doesn't handle slashes in the db name (if I'm not mistaken, didn't actually try it but the code looks like it doesn't). `foo/bar/baz` is a valid db name.

**Comment by cmbrandenburg** [comment]
@jgillich I too have been working on this. See [this branch](https://github.com/chill-rs/chill/tree/view_execution) and maybe [this file](https://github.com/chill-rs/chill/blob/view_execution/src/action/execute_view.rs). Please note I'll be squashing this branch into `master`, which I expect to happen by Wednesday. I'll get only the default options to work in this branch, so that leaves open all the work for the optional query parameters—e.g., `startkey`, `endkey`, `reduce`, etc. I'm hinting at my hope that you'll wait a few days for me to get my branch into `master`, then help with fleshing out the details.

The branch introduces new name and path types—just like you suggested—`ViewName`, `ViewPath`, `DesignDocumentPath`, and the  -`Ref` equivalents.

The no-slashes-in-the-name issue is a known limitation and affects only paths constructed from string literals. Applications may work around this limitation by constructing paths from constituent parts. E.g.,

```rust
"/foo".into_database_name().unwrap();     // ok
"/foo/bar".into_database_name().unwrap(); // panics: too many segments

let db_name = DatabaseNameRef::from("foo/bar"); // ok, cannot fail
db_name.into_database_name().unwrap();          // ok, conversion from name will never fail

// When sent as an HTTP request, the database path will be percent-encoded as /foo%2Fbar.
```

The rationale here is that it's easy for an application programmer to make a mistake if it's their responsibility to do any percent-encoding, so *Chill hides all percent-encoding from the application*. One consequence is the limitation that applications cannot construct paths from string literals. The kicker for me in deciding this is that document names can contain `%` characters, so percent-encoding would be ambiguous when constructing paths from strings. E.g.,

```rust
"/foo/bar%25qux".into_document_name().unwrap(); // ok, but...
// What is the intended percent-encoded path?
//   1. /foo/bar%25qux, or,
//   2. /foo/bar%2525qux
// Both are valid. But Chill will encode as choice #2.
```

I.e., by having one simple rule—Chill hides all percent-encoding from the application—Chill provides an API that achieves a good balance of convenience and safety. Also, this is the reason applications cannot construct paths from strings constructed at runtime. E.g.,

```rust
let db_name = "foo";
let doc_id = "bar/qux";
let s = format!("/{}/{}", db_name, doc_id);
s.into_document_path().unwrap();              // does not compile: ambiguous
"/foo/bar/qux".into_document_path().unwrap(); // compiles but panics: too many segments
```

The `format!` call is too likely to be written and then _untested_, so Chill disallows it. Whereas, a programmer is more likely to recognize an ambiguous path as a string literal—because they're looking right at it!—and the convenience of being able to hard-code a string here and there is too important to give up, so Chill allows it. This is all part of Chill's three design goals of _convenience_, _type-safety_, and _efficiency_—in decreasing order of importance.

I plan to blog about the percent-encoding issue in depth because it exposes interesting design decisions. In the meantime, the closest any of this is to being documented is in the [path module API documentation](https://chill-rs.github.io/chill/doc/v0.1.0/chill/path/index.html)—and in this comment, I guess. If you feel any of the documentation is unclear or incomplete, then please submit an issue or a patch. It's hard for me to know what's obvious and what's non-obvious because I've been thinking about CouchDB in Rust for a long time now.

**Comment by jgillich** [comment]
That sounds reasonable, thanks! The docs cover this in very well, I just didn't read (all of) them.
